[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://magicstream.netlify.app"
  to = "https://magickids.live"
  status = 301
  force = true
  headers = {X-From = "Netlify"}